In [21]:
import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/prathamd69/datasets/refs/heads/main/healthdataset.csv')

In [22]:
df['Health_Status'].unique()

array(['Healthy', 'Overweight', 'Obese', 'Underweight'], dtype=object)

In [2]:
df.describe()

,Age,Height_cm,Weight_kg,BMI,Daily_Calorie_Requirement,Daily_Calorie_Consumed,Protein_Intake_g,Carbohydrate_Intake_g,Fat_Intake_g,Water_Intake_Liters
count,6000.000000,6000.000000,6000.000000,6000.000000,6000.000000,6000.000000,6000.000000,6000.000000,6000.000000,6000.000000
mean,48.817167,168.592533,74.070933,26.094300,2286.223833,2490.520333,123.773150,288.035317,93.698417,2.734917
std,18.141837,9.160213,12.417877,4.162643,469.541134,602.279679,61.999158,123.914738,43.953993,0.681486
min,18.000000,145.000000,40.000000,12.900000,1223.000000,1000.000000,17.400000,-23.600000,23.200000,1.500000
25%,33.000000,161.700000,65.500000,23.300000,1941.000000,2057.000000,78.800000,229.100000,65.900000,2.200000
50%,48.000000,168.200000,74.100000,26.000000,2232.500000,2433.000000,108.900000,297.150000,82.300000,2.600000
75%,65.000000,175.200000,82.700000,28.900000,2581.250000,2859.000000,155.100000,366.125000,105.100000,3.100000
max,80.000000,198.600000,116.600000,44.000000,4079.000000,5158.000000,457.500000,729.700000,341.700000,5.000000

In [3]:
df.head()

,Person_ID,Age,Gender,Height_cm,Weight_kg,BMI,Activity_Level,Daily_Calorie_Requirement,Daily_Calorie_Consumed,Protein_Intake_g,Carbohydrate_Intake_g,Fat_Intake_g,Water_Intake_Liters,Diet_Type,Health_Status
0,P0001,50,Male,176.4,74.8,24.0,Very Active,2852,2625,183.0,16.9,202.8,3.3,Keto,Healthy
1,P0002,18,Female,167.6,75.5,26.9,Sedentary,1904,2044,90.1,306.5,50.8,1.9,Vegan,Overweight
2,P0003,68,Female,161.9,87.2,33.3,Lightly Active,2009,2540,222.7,281.3,58.2,2.4,High Protein,Obese
3,P0004,22,Female,169.3,66.9,23.3,Moderately Active,2318,2096,69.5,299.8,68.7,2.9,Balanced,Healthy
4,P0005,30,Male,179.1,75.3,23.5,Sedentary,2144,1937,32.9,285.6,73.7,2.2,Balanced,Healthy

In [28]:
df['Activity_Level'].unique()

array(['Very Active', 'Sedentary', 'Lightly Active', 'Moderately Active',
       'Athlete'], dtype=object)

In [4]:
df['daily_calorie_index'] = df['Daily_Calorie_Consumed'] - df['Daily_Calorie_Requirement']
df = df.drop(columns=['Daily_Calorie_Consumed', 'Daily_Calorie_Requirement'])

In [5]:
df = df.drop(columns=['Person_ID'])

In [31]:
df

,Age,Gender,Height_cm,Weight_kg,BMI,Activity_Level,Protein_Intake_g,Carbohydrate_Intake_g,Fat_Intake_g,Water_Intake_Liters,Diet_Type,Health_Status,daily_calorie_index
0,50,Male,176.4,74.8,24.0,Very Active,183.0,16.9,202.8,3.3,Keto,Healthy,-227
1,18,Female,167.6,75.5,26.9,Sedentary,90.1,306.5,50.8,1.9,Vegan,Overweight,140
2,68,Female,161.9,87.2,33.3,Lightly Active,222.7,281.3,58.2,2.4,High Protein,Obese,531
3,22,Female,169.3,66.9,23.3,Moderately Active,69.5,299.8,68.7,2.9,Balanced,Healthy,-222
4,30,Male,179.1,75.3,23.5,Sedentary,32.9,285.6,73.7,2.2,Balanced,Healthy,-207
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5995,45,Female,161.1,79.1,30.5,Lightly Active,85.0,305.9,81.4,2.4,Balanced,Obese,257
5996,53,Female,157.7,63.7,25.6,Sedentary,177.0,179.7,47.1,1.8,High Protein,Overweight,296
5997,43,Female,154.0,81.8,34.5,Athlete,139.7,483.3,123.2,4.4,Mediterranean,Obese,761
5998,51,Female,162.8,77.8,29.4,Lightly Active,118.7,51.9,160.4,2.8,Keto,Overweight,132
5999,25,Male,171.5,75.9,25.8,Athlete,163.3,623.0,95.1,4.4,Vegan,Overweight,607

In [6]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

In [7]:
df['Gender'] = le.fit_transform(df['Gender'])

In [34]:
df

,Age,Gender,Height_cm,Weight_kg,BMI,Activity_Level,Protein_Intake_g,Carbohydrate_Intake_g,Fat_Intake_g,Water_Intake_Liters,Diet_Type,Health_Status,daily_calorie_index
0,50,1,176.4,74.8,24.0,Very Active,183.0,16.9,202.8,3.3,Keto,Healthy,-227
1,18,0,167.6,75.5,26.9,Sedentary,90.1,306.5,50.8,1.9,Vegan,Overweight,140
2,68,0,161.9,87.2,33.3,Lightly Active,222.7,281.3,58.2,2.4,High Protein,Obese,531
3,22,0,169.3,66.9,23.3,Moderately Active,69.5,299.8,68.7,2.9,Balanced,Healthy,-222
4,30,1,179.1,75.3,23.5,Sedentary,32.9,285.6,73.7,2.2,Balanced,Healthy,-207
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5995,45,0,161.1,79.1,30.5,Lightly Active,85.0,305.9,81.4,2.4,Balanced,Obese,257
5996,53,0,157.7,63.7,25.6,Sedentary,177.0,179.7,47.1,1.8,High Protein,Overweight,296
5997,43,0,154.0,81.8,34.5,Athlete,139.7,483.3,123.2,4.4,Mediterranean,Obese,761
5998,51,0,162.8,77.8,29.4,Lightly Active,118.7,51.9,160.4,2.8,Keto,Overweight,132
5999,25,1,171.5,75.9,25.8,Athlete,163.3,623.0,95.1,4.4,Vegan,Overweight,607

In [8]:
from sklearn.preprocessing import OrdinalEncoder
ordered_categories = [['Sedentary', 'Lightly Active', 'Moderately Active', 'Very Active', 'Athlete']]

# Initialize the encoder with your specific hierarchy
encoder = OrdinalEncoder(categories=ordered_categories)
df['Activity_Encoded'] = encoder.fit_transform(df[['Activity_Level']])
df = df.drop(columns=['Activity_Level'])

In [9]:
df = df.drop(columns=['Height_cm','Weight_kg'])

In [39]:
df

,Age,Gender,BMI,Protein_Intake_g,Carbohydrate_Intake_g,Fat_Intake_g,Water_Intake_Liters,Diet_Type,Health_Status,daily_calorie_index,Activity_Encoded
0,50,1,24.0,183.0,16.9,202.8,3.3,Keto,Healthy,-227,3.0
1,18,0,26.9,90.1,306.5,50.8,1.9,Vegan,Overweight,140,0.0
2,68,0,33.3,222.7,281.3,58.2,2.4,High Protein,Obese,531,1.0
3,22,0,23.3,69.5,299.8,68.7,2.9,Balanced,Healthy,-222,2.0
4,30,1,23.5,32.9,285.6,73.7,2.2,Balanced,Healthy,-207,0.0
...,...,...,...,...,...,...,...,...,...,...,...
5995,45,0,30.5,85.0,305.9,81.4,2.4,Balanced,Obese,257,1.0
5996,53,0,25.6,177.0,179.7,47.1,1.8,High Protein,Overweight,296,0.0
5997,43,0,34.5,139.7,483.3,123.2,4.4,Mediterranean,Obese,761,4.0
5998,51,0,29.4,118.7,51.9,160.4,2.8,Keto,Overweight,132,1.0
5999,25,1,25.8,163.3,623.0,95.1,4.4,Vegan,Overweight,607,4.0

In [40]:
df['Health_Status'].unique()

array(['Healthy', 'Overweight', 'Obese', 'Underweight'], dtype=object)

In [10]:
rem = [[ 'Underweight','Healthy', 'Overweight', 'Obese']]

# Initialize the encoder with your specific hierarchy
encoder = OrdinalEncoder(categories=rem)
df['target'] = encoder.fit_transform(df[['Health_Status']])
df = df.drop(columns=['Health_Status'])

In [11]:
df

,Age,Gender,BMI,Protein_Intake_g,Carbohydrate_Intake_g,Fat_Intake_g,Water_Intake_Liters,Diet_Type,daily_calorie_index,Activity_Encoded,target
0,50,1,24.0,183.0,16.9,202.8,3.3,Keto,-227,3.0,1.0
1,18,0,26.9,90.1,306.5,50.8,1.9,Vegan,140,0.0,2.0
2,68,0,33.3,222.7,281.3,58.2,2.4,High Protein,531,1.0,3.0
3,22,0,23.3,69.5,299.8,68.7,2.9,Balanced,-222,2.0,1.0
4,30,1,23.5,32.9,285.6,73.7,2.2,Balanced,-207,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...
5995,45,0,30.5,85.0,305.9,81.4,2.4,Balanced,257,1.0,3.0
5996,53,0,25.6,177.0,179.7,47.1,1.8,High Protein,296,0.0,2.0
5997,43,0,34.5,139.7,483.3,123.2,4.4,Mediterranean,761,4.0,3.0
5998,51,0,29.4,118.7,51.9,160.4,2.8,Keto,132,1.0,2.0
5999,25,1,25.8,163.3,623.0,95.1,4.4,Vegan,607,4.0,2.0

In [13]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

onehotenc = OneHotEncoder(sparse_output=False)
onehotenc.fit(df[['Diet_Type']])
diet_encoded = onehotenc.transform(df[['Diet_Type']])

if hasattr(diet_encoded, "toarray"):
                diet_encoded_array = diet_encoded.toarray() # type:ignore
else:
                diet_encoded_array = diet_encoded

diet_encoded_df = pd.DataFrame(
diet_encoded_array, # type:ignore
columns=onehotenc.get_feature_names_out(['Diet_Type']),
index=df.index
            )   # type:ignore
df = pd.concat([df, diet_encoded_df], axis=1)

In [16]:
df = df.drop(columns=['Diet_Type'])

In [17]:
corr_matrix = df.corr()
corr_matrix.style.background_gradient(
    cmap="coolwarm", vmin=-1, vmax=1
).format(precision=2)

In [18]:
df = df.drop(columns=['Diet_Type_Balanced',	'Diet_Type_High Protein',
                                  'Diet_Type_Keto', 'Diet_Type_Mediterranean',
                                  'Diet_Type_Vegan', 'Diet_Type_Vegetarian',
                                  'Gender', 'Water_Intake_Liters'])

In [19]:
df

,Age,BMI,Protein_Intake_g,Carbohydrate_Intake_g,Fat_Intake_g,daily_calorie_index,Activity_Encoded,target
0,50,24.0,183.0,16.9,202.8,-227,3.0,1.0
1,18,26.9,90.1,306.5,50.8,140,0.0,2.0
2,68,33.3,222.7,281.3,58.2,531,1.0,3.0
3,22,23.3,69.5,299.8,68.7,-222,2.0,1.0
4,30,23.5,32.9,285.6,73.7,-207,0.0,1.0
...,...,...,...,...,...,...,...,...
5995,45,30.5,85.0,305.9,81.4,257,1.0,3.0
5996,53,25.6,177.0,179.7,47.1,296,0.0,2.0
5997,43,34.5,139.7,483.3,123.2,761,4.0,3.0
5998,51,29.4,118.7,51.9,160.4,132,1.0,2.0
5999,25,25.8,163.3,623.0,95.1,607,4.0,2.0